apiVersion: v1
kind: Service
metadata:
  name: api-rate-limiter
  namespace: {{ .Values.apiRateLimiter.namespace }}
  labels:
    {{- include "apiRateLimiter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiRateLimiter.service.type }}
  ports:
    - port: {{ .Values.apiRateLimiter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apiRateLimiter.selectorLabels" . | nindent 4 }}
  {{- with .Values.apiRateLimiter.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
