{{- if .Values.protectedApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: protected-api
  labels:
    {{- include "apiRateLimiter.labels" . | nindent 4 }}
  {{- with .Values.protectedApi.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.protectedApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
